# Generated by Django 4.2.16 on 2024-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.PositiveSmallIntegerField()),
                ('passes', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('no_of_goals', models.IntegerField()),
                ('shots_on_target', models.PositiveIntegerField()),
            ],
        ),
    ]
