# Generated by Django 4.2.16 on 2024-10-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0003_footballvideo_delete_videoanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballvideo',
            name='player_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
