# Generated by Django 4.2.16 on 2024-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0004_footballvideo_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballvideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='footballvideo',
            name='player_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
