# Generated by Django 4.2.16 on 2024-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0006_remove_footballvideo_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballvideo',
            name='player_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='footballvideo',
            name='shooting_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballvideo',
            name='shooting_angle',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
