# Generated by Django 4.2.16 on 2024-10-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0008_alter_footballvideo_shooting_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballvideo',
            name='player_name',
        ),
    ]
