# Generated by Django 4.2.16 on 2024-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('video_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.PositiveSmallIntegerField()),
                ('video_description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('shooting_accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('shooting_angle', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
