# Generated by Django 4.2.16 on 2024-10-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0002_rename_accuracy_videoanalysis_shooting_accuracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shooting_accuracy', models.FloatField(blank=True, null=True)),
                ('shooting_angle', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoAnalysis',
        ),
    ]
