# Generated by Django 4.2.16 on 2024-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0007_footballvideo_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballvideo',
            name='shooting_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='footballvideo',
            name='shooting_angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
