name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libsm6 libxext6 libxrender1

      - name: Install NumPy first
        run: |
          pip install numpy>=1.24.0

      - name: Install other dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Git remote for Heroku
        run: |
          git remote add heroku https://git.heroku.com/sportus.git || echo "Heroku remote already exists"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "sportus"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpacks: "https://github.com/heroku/heroku-buildpack-apt,heroku/python"
